### ISSUE TITLE
Need to add a little better error checking for the product class. List > cost ? price > cost?. Maybe an override switch?

### ISSUE THREAD

**Issue by bj-rutledge** [bj-rutledge/CRUD-API-Example#13]
Currently the Product class has minimal error checking. It is a good idea to make sure the price is greater than the cost, and if not, require an override.

**Comment by stawuah** [comment]
Hi @bj-rutledge  It's Stephen from  LinkedIn , as a good first issue i decided to come up with a solution before i create a branch 🛩️ ,

The solution is to add an override switch for error check.  

1. So adding a method to the Product class that allows for overriding the error check
2. The method then checks if the price is less than or equal to the cost. If this condition is met, it logs an error.
3. The method then allows bypassing the price check only if price is greater than cost  


This way, override switch for error check  provides flexibility while ensuring that the check is only bypassed in valid scenarios.

**Comment by bj-rutledge** [comment]
That sounds like what I have planned, so I am happy to let you take a crack at it. 

Though this is a fictional buisnes API,  I want to have features such as this, because, in business, sometimes you have to sell below the cost of good. 

Looks forward to seeing what you do!

**Comment by stawuah** [comment]
Hi, I have made PR , it needs a reviewer kindly review it .

**Comment by bj-rutledge** [comment]
PR merged. Thanks!
